import requests
import re
import datetime
import os

# List of source M3U playlists
SOURCES = [
    "https://raw.githubusercontent.com/abusaeeidx/Mrgify-BDIX-IPTV/main/playlist.m3u",
    "https://raw.githubusercontent.com/FunctionError/PiratesTv/main/combined_playlist.m3u"
]

def fetch_playlist(url):
    try:
        # Added headers to mimic a browser and avoid being blocked
        headers = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
        }
        response = requests.get(url, headers=headers, timeout=20)
        if response.status_code == 200:
            return response.text
        else:
            print(f"Failed to fetch {url}: Status {response.status_code}")
            return None
    except Exception as e:
        print(f"Error fetching {url}: {e}")
        return None

def parse_m3u(content):
    channels = []
    # Advanced regex to handle various M3U formats and metadata
    # Pattern looks for #EXTINF, then any metadata, then the channel name, followed by the URL
    lines = content.splitlines()
    current_extinf = None
    
    for line in lines:
        line = line.strip()
        if not line:
            continue
        if line.startswith("#EXTINF:"):
            current_extinf = line
        elif line.startswith("http"):
            if current_extinf:
                channels.append((current_extinf, line))
                current_extinf = None
    return channels

def clean_extinf(extinf):
    # Standardize metadata to make it look cleaner
    # Remove redundant source-specific tags if any
    return extinf

def main():
    all_channels = []
    seen_urls = set()

    print(f"Starting Scraper at {datetime.datetime.now()}")

    for source in SOURCES:
        print(f"Processing source: {source}")
        content = fetch_playlist(source)
        if content:
            channels = parse_m3u(content)
            count = 0
            for extinf, url in channels:
                # Basic duplicate removal and filtering
                if url not in seen_urls and not any(x in url.lower() for x in ['ads', 'click-here']):
                    all_channels.append((clean_extinf(extinf), url))
                    seen_urls.add(url)
                    count += 1
            print(f"  - Found {count} unique channels from this source.")
    
    # Generate the combined playlist
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    header = f"""#EXTM3U
#=========================================================
# 🇳🇵 NEPAL IPTV AUTO-UPDATED PLAYLIST 🇳🇵
#=========================================================
# Generated by: NEPAL-IPTV Bot
# Last Updated: {timestamp} (UTC)
# Total Channels: {len(all_channels)}
# Support: https://github.com/BalochLeader/NEPAL-IPTV
#=========================================================
"""
    
    output_file = "nepal_iptv.m3u"
    with open(output_file, "w", encoding="utf-8") as f:
        f.write(header)
        for extinf, url in all_channels:
            f.write(f"{extinf}\n{url}\n")
            
    print(f"Successfully generated {output_file} with {len(all_channels)} channels.")

if __name__ == "__main__":
    main()
